s3:
  bucket: rbi-data-workday-exports
  key: org-report.csv

files:
  users_tf: C:\Users\rbipz002\Documents\GitHub\rbi-snowflake\.snowflake\modules\account\users.tf
  users_sql: C:\Users\rbipz002\Documents\GitHub\rbi-snowflake\.snowflake\modules\snowflake_cost\sql\dim\users.sql
  grants_tf: C:\Users\rbipz002\Documents\GitHub\rbi-snowflake\.snowflake\modules\account\grants.tf
  masking_policies_tf: C:\Users\rbipz002\Documents\GitHub\rbi-snowflake\.snowflake\modules\account\masking_policies.tf

exclude_users:
  - keboola_bk
  - keboola_fhs
  - keboola_plk
  - keboola_th
  - bk_missing_items_reader
  - bk_strategy
  - fzconnect
  - streamlit_creator
  - amplitude_bk
  # Add more machine users as needed

exclude_emails:
  - PPATEL@RBI.COM
  - LKUMAR1@RBI.COM
  # Add more user emails to exclude from removal here
